# Action name
name: build

# Here, this action will be enabled on all pushes.
# Modify this to fit your needs.
on:
    push:
    workflow_dispatch:

# Jobs section
jobs:
    # The job that will use the container image you just pushed to ghcr.io
    build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
              with:
                submodules: recursive
                token: ${{ secrets.PAT }}
            
            # Ensure Rosetta is installed
            - name: Install Rosetta
              shell: bash
              run: |
                softwareupdate --install-rosetta --agree-to-license

            - name: build_step
              shell: bash
              run: |
                git config --global --add safe.directory /__w/MCUViewer/
                arch -x86_64 ./launch/release.sh

            - uses: actions/upload-artifact@v4
              with:
                name: MCUViewer_installer
                path: ./build/packages/
    test:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
              with:
                submodules: recursive
                token: ${{ secrets.PAT }}
            
            # Ensure Rosetta is installed
            - name: Install Rosetta
              shell: bash
              run: |
                softwareupdate --install-rosetta --agree-to-license
                
            - name: test_step
              shell: bash
              run: |
                git config --global --add safe.directory /__w/MCUViewer/
                arch -x86_64 ./launch/run_tests.sh
